name: CreatieveVrienden
favicon: null
layout_spectrum: 0.24899
typography_spectrum: 0.24879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ea168c'
    - '#ffffff'
    - '#231f20'
    - '#fac5e3'
    - '#f374be'
  brandStrength: 1
  lightness: 0.3444701989647001
  saturation: 0.4614232424646616
  rhythmicContrast: 0.45051791588775814
purpose: []
