name: CreatieveVrienden
favicon: null
layout_spectrum: 0.7003484789747745
typography_spectrum: 0.5821211768779904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.04643090674653649
  lightness: 0.3444701989647001
  saturation: 0.4614232424646616
  rhythmicContrast: 0.45051791588775814
purpose: []
